refresh_device:
  name: Refresh Device
  description: Force refresh a specific Gira X1 device
  fields:
    device_id:
      name: Device ID
      description: The device ID to refresh
      required: true
      selector:
        text:

set_raw_value:
  name: Set Raw Value
  description: Set a raw value for a Gira X1 function
  fields:
    function_id:
      name: Function ID
      description: The function ID to control
      required: true
      selector:
        text:
    value:
      name: Value
      description: The value to set
      required: true
      selector:
        number:
          min: 0
          max: 100
